const channels = [
	{
		id: '1238731980',
		title: 'Bagramyan 26',
		username: 'bagramyan26',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{ id: '2533723819', title: 'Test', username: 'N/A' },
	{
		id: '1056597437',
		title: 'IRGC News Channel',
		username: 'sepah_pasdaran',
		language: 'Persian',
		typical_topics: [
			'Isreal-Iran War',
			'Iranian Internal Politics',
			'Iranian Foreign Relations',
			'Zionist attacks',
		],
	},
	{
		id: '1781480731',
		title: 'Resistance News Network',
		username: 'PalestineResist',
		language: 'English',
		typical_topics: [
			'Isreal-Palestine War',
			'Palestinian Internal Politics',
			'Palestinian Foreign Relations',
			'Zionist attacks',
		],
	},
	{
		id: '2110961204',
		title: 'Praxis Redacted Official',
		username: 'N/A',
		language: 'English',
		typical_topics: [
			'Isreal-Iran War',
			'Isreal-Palestine War',
			'Israeli Military',
			'Israeli Internal Politics',
			'Zionist attacks',
		],
	},
	{
		id: '1237876926',
		title: 'Armenian Military Portal',
		username: 'military_arm',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{ id: '1448634950', title: 'Ararat', username: 'ararathau', language: 'Russian' },
	{
		id: '1299040538',
		title: 'Re:public of Artsakh',
		username: 'reartsakh',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1410082551',
		title: 'Armenian Life',
		username: 'Armenian_Life',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1419454128',
		title: 'China Army',
		username: 'china3army',
		language: 'Russian',
		typical_topics: ['China-Taiwan Conflict', 'Chinese Diplomacy', 'Chinese Foreign Relations', 'Chinese News'],
	},
	{
		id: '1585934836',
		title: 'China Brief',
		username: 'Chinabrief',
		language: 'Russian',
		typical_topics: ['China-Taiwan Conflict', 'Chinese Diplomacy', 'Chinese Foreign Relations', 'Chinese News'],
	},
];

export default channels;
