const channels = [
	{
		id: '1238731980',
		title: 'Bagramyan 26',
		username: 'bagramyan26',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{ id: '2533723819', title: 'Test', username: 'N/A' },
	{
		id: '1056597437',
		title: 'IRGC News Channel',
		username: 'sepah_pasdaran',
		language: 'Persian',
		typical_topics: [
			'Isreal-Iran War',
			'Iranian Internal Politics',
			'Iranian Foreign Relations',
			'Zionist attacks',
		],
	},
	{
		id: '1781480731',
		title: 'Resistance News Network',
		username: 'PalestineResist',
		language: 'English',
		typical_topics: [
			'Isreal-Palestine War',
			'Palestinian Internal Politics',
			'Palestinian Foreign Relations',
			'Zionist attacks',
		],
	},
	{
		id: '2110961204',
		title: 'Praxis Redacted Official',
		username: 'N/A',
		language: 'English',
		typical_topics: [
			'Isreal-Iran War',
			'Isreal-Palestine War',
			'Israeli Military',
			'Israeli Internal Politics',
			'Zionist attacks',
		],
	},
	{
		id: '1237876926',
		title: 'Armenian Military Portal',
		username: 'military_arm',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1448634950',
		title: 'Ararat',
		username: 'ararathau',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1299040538',
		title: 'Re:public of Artsakh',
		username: 'reartsakh',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1410082551',
		title: 'Armenian Life',
		username: 'Armenian_Life',
		language: 'Russian',
		typical_topics: [
			'Isreal-Iran War',
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1419454128',
		title: 'China Army',
		username: 'china3army',
		language: 'Russian',
		typical_topics: ['China-Taiwan Conflict', 'Chinese Diplomacy', 'Chinese Foreign Relations', 'Chinese News'],
	},
	{
		id: '1585934836',
		title: 'China Brief',
		username: 'Chinabrief',
		language: 'Russian',
		typical_topics: ['China-Taiwan Conflict', 'Chinese Diplomacy', 'Chinese Foreign Relations', 'Chinese News'],
	},
	{
		id: '1002400952',
		title: 'Quds News Network',
		username: 'QudsN',
		language: 'Arabic',
		typical_topics: [
			'Isreal-Iran War',
			'Palestinian Internal Politics',
			'Palestinian Foreign Relations',
			'Zionist attacks',
			'Levantine News',
			'Middle East',
		],
	},
	{
		id: '1002129373',
		title: 'Al Mayadeen',
		username: 'almayadeen',
		language: 'Arabic',
		typical_topics: [
			'Isreal-Iran War',
			'Palestinian Internal Politics',
			'Palestinian Foreign Relations',
			'Zionist attacks',
			'Levantine News',
			'Middle East',
		],
	},
	{
		id: '1497314205',
		title: 'Solcu Gazete',
		username: 'solcugazete',
		language: 'Turkish',
		typical_topics: ['Turkish News', 'Turkish Politics', 'Middle East'],
	},
	{
		id: '1209835753',
		title: 'Operativ Məlumat Mərkəzi',
		username: 'operativmm',
		language: 'Azerbaijani',
		typical_topics: [
			'Azerbaijani Politics',
			'Armenian Military',
			'Azerbaijani Military',
			'Azerbaijani Foreign Relations',
		],
		special_instructions:
			"Disregard messages that cover the Iran-Isreal or the Isreal-Palestine war that don't explicitly mention Azerbaijan or an Azerbaijani figure. This channel supports a genocidal regime. Special care must be taken with it's news. If there is news regarding Armenians that paints them in a bad light, add a note describing this channel's Pro-Azerbaijan leanings and Azerbaijan's genocidal rhetoric.",
	},
	{
		id: '1429317034',
		title: 'Borneni Efektivi',
		username: 'borbeni_efektivi',
		language: 'Serbian',
		typical_topics: ['Serbian News', 'European Politics'],
		special_instructions:
			"Disregard messages that cover the Iran-Isreal or the Isreal-Palestine war that don't explicitly mention a Balkan country or a Balkan figure. This channel might have a right-wing lean. If it does, add a note about the channel's right-wing bias.",
	},
	{
		id: '1236996847',
		title: 'Xəbər Azərbaycan',
		username: 'Xebervar',
		language: 'Azerbaijani',
		typical_topics: [
			'Azerbaijani Politics',
			'Armenian Military',
			'Azerbaijani Military',
			'Azerbaijani Foreign Relations',
		],
		special_instructions:
			"Disregard messages that cover the Iran-Isreal or the Isreal-Palestine war that don't explicitly mention Azerbaijan or an Azerbaijani figure. This channel supports a genocidal regime. Special care must be taken with it's news. If there is news regarding Armenians that paints them in a bad light, add a note describing this channel's Pro-Azerbaijan leanings and Azerbaijan's genocidal rhetoric.",
	},
	{
		id: '1327639291',
		title: 'Armenpress',
		username: 'armenpress',
		language: 'Russian',
		typical_topics: [
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1261204283',
		title: 'Novosti-Armeniya',
		username: 'N/A',
		language: 'Russian',
		typical_topics: [
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1462957310',
		title: 'Yerevan․Today Rus',
		username: 'rusyerevantoday',
		language: 'Russian',
		typical_topics: [
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},

	{
		id: '1764399953',
		title: 'Girl with a Gun',
		username: 'leontinakoen',
		language: 'Armenian, Russian',
		typical_topics: [
			'Armenian Military',
			'Armenian Internal Politics',
			'Armenian Foreign Relations',
			'Armenian Diplomacy',
			'Azerbaijani Aggression',
			'Artsakh War',
		],
	},
	{
		id: '1231063061',
		title: 'Oxu',
		username: 'oxuaze',
		language: 'Azerbaijani',
		typical_topics: [
			'Azerbaijani Politics',
			'Armenian Military',
			'Azerbaijani Military',
			'Azerbaijani Foreign Relations',
		],
		special_instructions:
			"Disregard messages that cover the Iran-Isreal or the Isreal-Palestine war that don't explicitly mention Azerbaijan or an Azerbaijani figure. This channel supports a genocidal regime. Special care must be taken with it's news. If there is news regarding Armenians that paints them in a bad light, add a note describing this channel's Pro-Azerbaijan leanings and Azerbaijan's genocidal rhetoric.",
	},
	{
		id: '1288049982',
		title: 'Musavat',
		username: 'TVmusavat',
		language: 'Azerbaijani',
		typical_topics: [
			'Azerbaijani Politics',
			'Armenian Military',
			'Azerbaijani Military',
			'Azerbaijani Foreign Relations',
		],
		special_instructions:
			"Disregard messages that cover the Iran-Isreal or the Isreal-Palestine war that don't explicitly mention Azerbaijan or an Azerbaijani figure. This channel supports a genocidal regime. Special care must be taken with it's news. If there is news regarding Armenians that paints them in a bad light, add a note describing this channel's Pro-Azerbaijan leanings and Azerbaijan's genocidal rhetoric.",
	},

	{
		id: '1350013005',
		title: 'Power from the East',
		username: 'silasaistoka',
		language: 'Serbian',
		typical_topics: ['Serbian News', 'European Politics'],
		special_instructions:
			"Disregard messages that cover the Iran-Isreal or the Isreal-Palestine war that don't explicitly mention a Balkan country or a Balkan figure. This channel might have a right-wing lean. If it does, add a note about the channel's right-wing bias.",
	},

	{
		id: '1635002934',
		title: 'Army of the Republic of Serbia',
		username: 'debeljaca1vrs',
		language: 'Serbian',
		typical_topics: ['Serbian News', 'European Politics'],
		special_instructions:
			"Disregard messages that cover the Iran-Isreal or the Isreal-Palestine war that don't explicitly mention a Balkan country or a Balkan figure. This channel might have a right-wing lean. If it does, add a note about the channel's right-wing bias.",
	},
];

export default channels;
